wsgi/source/apps/todo/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, include, url
from . import views


List_patterns = patterns(
    '',
    # list all List
    url(r'^list/$', views.ListListView.as_view(), name='list'),
    # show the List contain Item
    url(r'^detail/(?P<slug>[-\w]+)/$', views.ListDetailView.as_view(), name='detail'),
    # url(r'^create/$', views.ListCreateView.as_view(), name='create'),
    url(r'^update/(?P<slug>[-\w]+)/$', views.ListUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<slug>[-\w]+)/$', views.ListDeleteView.as_view(), name='delete'),
)
Item_patterns = patterns(
    '',
    url(r'^detail/(?P<pk>\d+)/$',
        views.ItemDetailView.as_view(), name='detail'),
    url(r'^update/(?P<pk>\d+)/$',
        views.ItemUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$',
        views.ItemDeleteView.as_view(), name='delete'),
    url(r'^ajax/toggle/(?P<pk>\d+)/$', views.itemToggle, name='toggle'),
    url(r'^ajax/update/(?P<pk>\d+)/$', views.AjaxUpdateView.as_view(), name='ajaxUpdate'),
)
#Comment_patterns = patterns(
#    '',
#    url(r'^update/(?P<pk>\d+)/$',
#        views.CommentUpdateView.as_view(), name='update'),
#    url(r'^delete/(?P<pk>\d+)/$',
#        views.CommentDeleteView.as_view(), name='delete'),
#)


urlpatterns = patterns(
    '',
    url(r'^list/', include(List_patterns, namespace='list')),
    url(r'^item/', include(Item_patterns, namespace='item')),
)

wsgi/source/etc/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView
from apps.blog.sitemaps import EntrySiteMap

urlpatterns = patterns(
    '',
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^account/', include('apps.account.urls', namespace='account')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(pattern_name = 'blog:entry:list'), name="index"),
    url(r'^todo/', include('apps.todo.urls', namespace='todo')),
)

if settings.SEARCH_ENGINE == 'HAYSTACK':
    urlpatterns += patterns(
        '',
        url(r'^search/', include('haystack.urls')),
    )

# debug toolbar
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += patterns(
#         '',
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     )

sitemaps = {
    'blog': EntrySiteMap,
}
urlpatterns += (
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

wsgi/source/apps/todo/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
import datetime
from django.contrib.auth.models import User
from . import managers
from utils import uniqueSlugify


class List(models.Model):
    objects = managers.ListFkManager()
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60, editable=False)
    author = models.ForeignKey(
        User,
        related_name='todo_list',
    )

    def save(self, *args, **kwargs):
        if not self.id:
            slug_str = "%s %s" % (self.author.username, self.name)
            #print(slug_str) 
            uniqueSlugify.unique_slugify(self, slug_str)
            #print(self.slug)
        super().save(*args, **kwargs)
    
    @classmethod
    def serialize_field(cls):
        return("name",)
        
    def __str__(self):
        return self.name


    def getTitle(self):
        return self.name

    def is_owner(self, user):
        return self.author == user
    
    def get_relate_items(self):
        return self.item_set.all()

    def incomplete_tasks(self):
        # Count all incomplete tasks on the current list instance
        return Item.objects.filter(list=self, completed=False)
        
    def incomplete_tasks_count(self):
        # Count all incomplete tasks on the current list instance
        return self.incomplete_tasks().count()
    
    def complete_tasks(self):
        return Item.objects.filter(list=self, completed=True)

    def complete_tasks_count(self):
        return self.complete_tasks().count()
        
    def get_absolute_url(self):
        return reverse('todo:list:detail', kwargs={'slug':self.slug})
    
    def get_update_url(self):
        return reverse('todo:list:update', kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse('todo:list:delete', kwargs={'slug':self.slug})
    
    def getModelName(self):
        return self.__class__.__name__
        
    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Lists"

        # Prevents (at the database level) creation of two lists with the same name in the same group
        unique_together = ("slug",)
class Item(models.Model):
    LOW = 0
    MIDDLE = 1
    HIGH = 2
    Priority_CHOICES = (
        (LOW, 'LOW'),
        (MIDDLE, 'MIDDLE'),
        (HIGH, 'HIGH'),
    )
    title = models.CharField(max_length=140)
    list = models.ForeignKey(List)
    created_date = models.DateField(auto_now_add=True)
    #due_date = models.DateField(blank=True, null=True, )
    completed = models.BooleanField(default=False)
    #completed_date = models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='todo_created_by')
    note = models.TextField(blank=True, null=True)
    priority = models.PositiveIntegerField(
        max_length=2, choices=Priority_CHOICES, default=MIDDLE)

    # Model method: Has due date for an instance of this object passed?
    # def overdue_status(self):
    #     "Returns whether the item's due date has passed or not."
    #     if self.due_date and datetime.date.today() > self.due_date:
    #         return 1
    @classmethod
    def serialize_field(cls):
        return("title", "note", "priority")
    def getTitle(self):
        return self.title

    def get_relate_list_url(self):
        return self.list.get_absolute_url()

    # def get_relate_comments(self):
    #     return self.comment_set.all()

    def get_absolute_url(self):
        return reverse('todo:item:detail', kwargs={'pk': self.id})

    def get_update_url(self):
        return reverse('todo:item:update', kwargs={'pk': self.id})

    def get_delete_url(self):
        return reverse('todo:item:delete', kwargs={'pk': self.id})

    def get_toggle_url(self):
        return reverse('todo:item:toggle', kwargs={'pk': self.id})

    def get_ajax_update_url(self):
        return reverse('todo:item:ajaxUpdate', kwargs={'pk':self.id})
    
    def __str__(self):
        return self.title

    def getModelName(self):
        return self._meta.verbose_name

    # Auto-set the item creation / completed date
    # def save(self):
    # If Item is being marked complete, set the completed_date
    #     if self.completed:
    #         self.completed_date = datetime.datetime.now()
    #     super().save()

    def is_owner(self, user):
        return self.created_by == user

    class Meta:
        ordering = ["completed", "-priority"]
# class Comment(models.Model):
#     """
#     Not using Django's built-in comments because we want to be able to save
#     a comment and change task details at the same time. Rolling our own since it's easy.
#     """
#     author = models.ForeignKey(User, related_name='todo_comment')
#     task = models.ForeignKey(Item)
#     date = models.DateTimeField(default=datetime.datetime.now)
#     body = models.TextField(blank=True)

#     def is_owner(self, user):
#         return self.author == user

#     def get_relate_task_url(self):
#         return self.task.get_absolute_url()

#     def get_update_url(self):
#         return reverse('todo:comment:update', kwargs={'pk': self.id})

#     def get_delete_url(self):
#         return reverse('todo:comment:delete', kwargs={'pk': self.id})

#     def getModelName(self):
#         return self.__class__.__name__

#     def getTitle(self):
#         return 'Comment to ' + self.task.getTitle() + ' on ' + str(self.date)

#     def snippet(self):
# Define here rather than in __str__ so we can use it in the admin list_display
# return "{author} - {snippet}...".format(author=self.author,
# snippet=self.body[:35])

#     def __str__(self):
#         return self.snippet()

wsgi/source/apps/todo/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views.generic.base import TemplateView, View, RedirectView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from . import models
from . import forms
from django.contrib import messages
from django.core.urlresolvers import reverse, reverse_lazy
from utils import mixins
from django.db.models import Count
import json
from django.core import serializers
from django.views.generic import View
from utils.mixins import RequireSignInAjax
from utils.mixins import JSONResponseMixin
from utils.mixins import HybridFormResponseMixin, HybridResponseMixin
from crispy_forms.utils import render_crispy_form
from django.views.generic.edit import FormMixin

class ListListView(mixins.LoginRequiredMixin, FormMixin, ListView):
    model = models.List
    template_name = "todo/List_list.html"
    context_object_name = "lists"
    form_class = forms.ListForm
    success_url = 'todo:list:list'
    
    def get_queryset(self):
        return models.List.objects.aviable(self.request.user)
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context['form'] = form
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            messages.add_message(
                self.request, messages.SUCCESS, 'List create success')
            obj = form.save(submitter=request.user)
            return redirect(reverse(self.success_url))
        else:
            return self.get(request, *args, **kwargs)

class ListDetailView(mixins.OwnerOrSuperuserMixin, HybridFormResponseMixin, HybridResponseMixin, FormMixin, DetailView):
    model = models.List
    template_name = "todo/List_detail.html"
    context_object_name = "list"
    form_class = forms.ItemForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        context['form'] = form
        return context
    
    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            messages.add_message(
                self.request, messages.SUCCESS, 'Item create success')
            obj = form.save(list_obj=self.get_object(), submitter=request.user)
            self.success_url = obj.list.get_absolute_url()
            return super().form_valid(form)
        else:
            #return self.get(request, *args, **kwargs)
            return super().form_is_invalid(form)
class ListCreateView(mixins.LoginRequiredMixin, CreateView):
    model = models.List
    template_name = 'todo/form.html'
    form = forms.ListForm
class ListUpdateView(mixins.OwnerOrSuperuserMixin, UpdateView):
    model = models.List
    form_class = forms.ListForm
    template_name = 'todo/form.html'
class ListDeleteView(mixins.OwnerOrSuperuserMixin, DeleteView):
    model = models.List
    success_url = reverse_lazy('todo:list:list')
    form_class = forms.ListForm
    template_name = 'todo/delete_form.html'
from django.http import JsonResponse
class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    
    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)
        else:
            return response
class ItemDetailView(mixins.OwnerOrSuperuserMixin, HybridResponseMixin, DetailView, FormView):
    model = models.Item
    template_name = "todo/Item_detail.html"
    context_object_name = "item"
    # form_class = forms.CommentForm

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['commentform'] = self.form_class
    #     return context

    # def post(self, request, *args, **kwargs):
    #     form_class = self.get_form_class()
    #     form = self.get_form(form_class)
    #     if form.is_valid():
    #         messages.add_message(
    #             self.request, messages.SUCCESS, 'comment create success')
    #         obj = form.save(task=self.get_object(), submitter=request.user)
    #         return redirect(obj.list)
    #     else:
    #         return self.get(request, *args, **kwargs)
class ItemUpdateView(mixins.OwnerOrSuperuserMixin, HybridResponseMixin, HybridFormResponseMixin, UpdateView):
    model = models.Item
    form_class = forms.ItemForm
    template_name = 'todo/form.html'

    def get_success_url(self):
        return self.get_object().get_relate_list_url()
        
    def get_form_kwargs(self):
        """
        Returns the keyword arguments for instantiating the form.
        """
        kwargs = super().get_form_kwargs()
        if hasattr(self, 'object'):
            kwargs.update({'instance': self.object})
        kwargs.update({'action':self.object.get_update_url()})
        return kwargs
class ItemDeleteView(mixins.OwnerOrSuperuserMixin, HybridResponseMixin,HybridFormResponseMixin, DeleteView):
    model = models.Item
    form_class = forms.ItemForm
    template_name = 'todo/delete_form.html'
    
    def get_success_url(self):
        return self.get_object().get_relate_list_url()
from django.core.serializers.json import DjangoJSONEncoder


def itemToggle(request, pk):
    if request.method == 'POST':
        item = models.Item.objects.get(pk=pk)
        if item:
            item.completed = not item.completed
            item.save()
            if request.is_ajax():
                response_data = {}
                response_data['result'] = 'edit item successful!'
                # tasks = models.Item.objects.filter(created_by=request.user)
                # task_list = [{"pk": task.id, "title": task.title, "note":
                #               task.note, "completed": task.completed} for task in tasks]
                # response_data['task_list'] = task_list
                status = 200
            else:
                return redirect(item.get_relate_list_url())
        else:
            if request.is_ajax():
                response_data['result'] = 'edit item fail!'
                status = 404
            else:
                messages.add_message(
                    self.request, messages.ERROR, 'The Item is not exist')
                return redirect(request.META.get('HTTP_REFERER'))
        return HttpResponse(json.dumps(response_data, cls=DjangoJSONEncoder), content_type="application/json", status=status)
class AjaxUpdateView(RequireSignInAjax, JSONResponseMixin, UpdateView):
    model = models.Item
    form_class = forms.ItemForm

    def get(self, request, *args, **kwargs):
        return self.render_to_response(self.get_context_data(**kwargs))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = render_crispy_form(self.form_class)
        return context

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
# update and delete view

#class CommentUpdateView(mixins.OwnerOrSuperuserMixin, UpdateView):
#    model = models.Comment
#    form_class = forms.CommentForm
#    template_name = 'todo/form.html'
#
#    def get_success_url(self):
#        return self.get_object().get_relate_task_url()
#class CommentDeleteView(mixins.OwnerOrSuperuserMixin, DeleteView):
#    model = models.Comment
#    form_class = forms.CommentForm
#    template_name = 'todo/delete_form.html'
#    
#    def get_success_url(self):
#        return self.get_object().get_relate_task_url()

wsgi/source/apps/todo/templates/todo/Item_detail.html
<h1>{{item.getTitle}}</h1>
<p>{{item.note}}</p>

<hr>

{% for comment in item.get_relate_comments %}
    <div class="comment">
        <div class="author">{{comment.author}}</div>
        <div class="date">{{comment.date}}</div>
        <div class="operate">
            <a href="{{ comment.get_update_url }}">Update</a>
            <a href="{{ comment.get_delete_url }}">Delete</a>
        <div>
        <div class="body">
            {{comment|safe}}
        </div>
    </div>
{% endfor %}

wsgi/source/apps/todo/templates/todo/List_delete_form.html
    <h3>do you really want to delete this {{object.getModelName}} - {{object.getTitle}}</h3>
<form method="post">
    <input type="submit" value="delete it">
</form>

wsgi/source/apps/todo/templates/todo/List_detail.html
{% extends "todo/base.html" %}
{% load static %}
{% load compress %}
{% load crispy_forms_tags %}
{% block pageName %}List-{{object.name}}{% endblock pageName %}
{% block extraCss %}
    <link rel="stylesheet" type="text/css" href="{% static "lib/bootstrap3-wysiwyg/bootstrap3-wysihtml5.min.css" %}">
    {% compress css %}
        <link rel="stylesheet" href="{% static "todo/css/Listdetail.css" %}">
    {% endcompress %}
{% endblock extraCss %}

{% block extraJsLib %}
    <script src="{% static "lib/bootstrap3-wysiwyg/bootstrap3-wysihtml5.all.min.js" %}" type="text/javascript"></script>
{% endblock extraJsLib %}

{% block body %}

<h1>List - {{object.name}}

<button class="btn btn-primary btn-lg" data-toggle="modal"
data-target="#ItemFormBlock">
    <i class="fa fa-plus fa-2x"></i>
</button>
<a href="{% url 'todo:list:list' %}" class="btn btn-info btn-lg"><i class="fa fa-backward fa-2x"></i>
</a>
</h1>

{# there is add itemForm #}

<div class="modal fade" id="ItemFormBlock" tabindex="-1" role="dialog"
    aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close"
                data-dismiss="modal" aria-hidden="true">
                &times;
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    Item Form
                </h4>
            </div>
            <div class="modal-body">
                {% crispy form %}
            </div>
        </div><!-- /.modal-content -->
    </div>
</div><!-- /.modal -->
{# end ItemForm #}

{# message block #}
<div id="msg"></div>
{# end message block#}

{% comment %}
div.tasks.block>ul.tasks>((li.task>div.task-headline>a.task-anchor{task $}^+div.task-content>p{this is task$ content})*10)
{% endcomment %}


<div class="tasks-block">
    <ul class="tasks">
    {% for obj in object.item_set.all %}


        <li completed="{{obj.completed}}" priority="{{obj.priority}}" class="task priority-{{obj.priority}}">
            <div class="task-headline">
                <div class="row">
                    <div class="col-sm-1">
                        <span class="togglebtn" href="{{obj.get_toggle_url}}">
                        </span>
                    </div>
                    <div class="col-sm-8">
                        <a href="#" class="completed-{{obj.completed}} task-anchor">{{obj.title}}</a>
                    </div>
                    <div class="col-sm-3 operation">
                        <a href="{{obj.get_update_url}}" class="updatebtn btn btn-primary btn-small"></a>
                        <a href="{{obj.get_delete_url}}" class="deletebtn btn btn-danger btn-small"></a>
                    </div>
                </div>
            </div>
            <div class="task-content">
                {{obj.note|safe}}
            </div>
        </li>
    {% endfor %}
    </ul>
</div>



{% endblock body %}

{% block extraJs %}

{% compress js %}
    <script src="{% static "js/ajax_csrf.js" %}"></script>
    <script src="{% static "todo/js/Listdetail.js" %}"></script>
{% endcompress %}
{% endblock extraJs %}

wsgi/source/apps/todo/templates/todo/List_detail.jinja
{% extends "todo/base.jinja" %}
{% block blockname %}List-{{list.name}}{% endblock blockname %}

{% block extraJsLib %}
    <script src="{{ static('js/ICanHaz.min.js') }}"></script>
    <script src="{{ static('lib/chosen/chosen.jquery.min.js') }}"></script>
    {#
        <link rel="stylesheet" type="text/css" href="{{ static('lib/datepicker/jquery.datepick.css') }}">
        <script type="text/javascript" src="{{ static('lib/datepicker/jquery.plugin.js') }}"></script>
        <script type="text/javascript" src="{{ static('lib/datepicker/jquery.datepick.js') }}"></script>
    #}
{% endblock extraJsLib %}

{% block extraCss %}
    <link rel="stylesheet" href="{{ static('lib/chosen/chosen.min.css') }}">
{% endblock extraCss %}




{% raw %}
<script id="incomplete" type="text/html">
    <li class="item">
        <div>
            <input class="completeBox" type="checkbox" href="{{toggle_url}}" />
        </div>
        <div>
            <div class="title"><a href="{{ absolute_url }}">{{title}}</a></div>
            <div class="operator">
                <a href="{{update_url}}">Update</a>
                <a href="{{delete_url}}">Delete</a>
            </div>
        <div>
    </li>
</script>

<script id="complete" type="text/html">
    <li class="item">
        <div>
            <input class="completeBox" type="checkbox" href="{{toggle_url}}" checked="checked" />
        </div>
        <div>
            <div class="title"><a href="{{ absolute_url }}">{{title}}</a></div>
            <div class="operator">
                <a href="{{update_url}}">Update</a>
                <a href="{{delete_url}}">Delete</a>
            </div>
        <div>
    </li>
</script>
{% endraw %}

{% block content %}
<h1> this is detail page <h1>

<h1>{{ list.name }}</h1>

<form method="POST">
    {% csrf_token %}
    {{ itemform().as_p()|safe }}
    <input type="submit" value="add list">
</form>


<div id="result"></div>

<h2>Incomplete Tasks</h2>

<ul id="incomplete_tasks">
{% for item in list.incomplete_tasks() %}
    <li class="item">
    <div>
        <input class="completeBox" type="checkbox" href="{{ url('todo:item:toggle' ,pk=item.id) }}" />
    </div>

    <div>
        <div class="title"><a href="{{ item.get_absolute_url }}">{{item.title}}</a></div>
        <div class="operator">
            <a href="{{item.get_update_url}}">Update</a>
            <a href="{{item.get_delete_url}}">Delete</a>
        </div>
    <div>

    </li>
{% endfor %}
</ul>


<h2>Complete Tasks</h2>


<ul id="complete_tasks">
{% for item in list.complete_tasks() %}
    <li class="item">
    <div>
        <input type="checkbox" class="completeBox" href="{{ url('todo:item:toggle', pk=item.id) }}" checked />
    </div>
    <div>
        <div class="title"><a href="{{ item.get_absolute_url }}">{{item.title}}</a></div>
        <div class="operator">
            <a href="{{item.get_update_url}}">Update</a>
            <a href="{{item.get_delete_url}}">Delete</a>
        </div>
    <div>

    </li>
{% endfor %}
</ul>
{% endblock content %}

{% block extraJs %}
<script>
    $(function(){
        $('body').on('change', '.completeBox', function(event){
            var anchor = $(this).parents(".item").find('.title>a');
            console.log(anchor.text());
            console.log(anchor.attr('href'));
            console.log($(this).attr('href'));
            console.log($(this).is(':checked'));
            $.ajax({
                url:$(this).attr('href'),
                type:'POST',
                success:function(json){
                    var result;
                    $("#result").html(json.result);

                    //console.log($.parseJSON(json.incompleted_items).length);

                    //var data = $.parseJSON(json.incompleted_items);
                    var incompleted_data = json.incompleted_items;
                    var completed_data = json.completed_items;
                    $('#incomplete_tasks').empty();
                    $('#complete_tasks').empty();
                    for(var i=0; i<incompleted_data.length; i++){
                        result = ich.incomplete(incompleted_data[i]);
                        $('#incomplete_tasks').append(result);
                    }
                    for(var i=0; i<completed_data.length; i++){
                        result = ich.complete(completed_data[i]);
                        $('#complete_tasks').append(result);
                    }

                },
                error:function(xhr, errmsg, err){
                    $("#result").html("Oops! We have encountered an error: "+errmsg)
                }
            });
            event.preventDefault();
        });
    });
</script>
<script>
$('#id_priority').chosen({allow_single_deselect:true});
//$('#id_due_date').datepick({dateFormat: 'yyyy-mm-dd'});
</script>


<script>
    // This function gets cookie with a given name
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    /*
    The functions below will create a header with csrftoken
    */

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    function sameOrigin(url) {
        // test that a given url is a same-origin URL
        // url could be relative or scheme relative or absolute
        var host = document.location.host; // host + port
        var protocol = document.location.protocol;
        var sr_origin = '//' + host;
        var origin = protocol + sr_origin;
        // Allow absolute or scheme relative URLs to same origin
        return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
            (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
            // or any other URL that isn't scheme relative or absolute i.e relative.
            !(/^(\/\/|http:|https:).*/.test(url));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
                // Send the token to same-origin, relative URLs only.
                // Send the token only if the method warrants CSRF protection
                // Using the CSRFToken value acquired earlier
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
</script>
{% endblock extraJs %}

wsgi/source/apps/todo/templates/todo/List_form.html
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

wsgi/source/apps/todo/templates/todo/base.jinja
{% extends "base.jinja" %}
{% block appName %}ToDo List{% endblock appName %}

wsgi/source/apps/todo/templates/todo/form.html
{% extends "todo/base.html" %}
{% load crispy_forms_tags %}
{% load compress %}
{% load static %}
{% block pageName %}Add/Edit Form{% endblock pageName %}
{% block body %}
    {% crispy form %}
{% endblock body %}

{% block extraCss %}
    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap3-wysiwyg/bootstrap3-wysihtml5.min.css' %}">
{% endblock extraCss %}

{% block extraJsLib %}
    <script src="{% static 'lib/bootstrap3-wysiwyg/bootstrap3-wysihtml5.all.min.js' %}" type="text/javascript"></script>
{% endblock extraJsLib %}

{% block extraJs %}
{% compress js inline %}
        <script>
        $('#id_note').wysihtml5({
              toolbar: {
                "font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
                "emphasis": true, //Italics, bold, etc. Default true
                "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
                "html": true, //Button which allows you to edit the generated HTML. Default false
                "link": true, //Button to insert a link. Default true
                "image": true, //Button to insert an image. Default true,
                "color": true, //Button to change color of font
                "blockquote": true, //Blockquote
                "size": "sm" //default: none, other options are xs, sm, lg
              }
        });
    </script>
{% endcompress %}
{% endblock extraJs %}