wsgi/source/apps/account/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .views import IndexView, LoginView, LogoutView, CreateUser, ChangePassWordView, PasswordResetConfirmView, ResetPasswordRequestView
from django.conf import settings


urlpatterns = patterns(
    '',
    url(r'^index/$', IndexView.as_view(), name='index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^changepassword/$', ChangePassWordView.as_view(),
        name='changepassword'),
)
if settings.OPEN_REGISTER:
    urlpatterns += patterns(
        '',
        url(r'^register/$', CreateUser.as_view(), name='register'),
    )
if settings.OPEN_FORGET_PASSWORD:
    urlpatterns += patterns(
        '',
        url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            PasswordResetConfirmView.as_view(), name='reset_password_confirm'),
        url(r'^reset_password/$', ResetPasswordRequestView.as_view(),
            name="reset_password"),
    )

wsgi/source/etc/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView
from apps.blog.sitemaps import EntrySiteMap

urlpatterns = patterns(
    '',
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^account/', include('apps.account.urls', namespace='account')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(pattern_name = 'blog:entry:list'), name="index"),
    url(r'^todo/', include('apps.todo.urls', namespace='todo')),
)

if settings.SEARCH_ENGINE == 'HAYSTACK':
    urlpatterns += patterns(
        '',
        url(r'^search/', include('haystack.urls')),
    )

# debug toolbar
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += patterns(
#         '',
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     )

sitemaps = {
    'blog': EntrySiteMap,
}
urlpatterns += (
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

wsgi/source/templates/401.html
{% extends "base.html" %}
{% block pageName %}401{% endblock pageName %}
{% block content %}
    <div class="center">
        <div class="headline">
            401 Unauthorized
        </div>
        <p>This action require login.</p>
    </div>
{% endblock content %}

wsgi/source/templates/base.html
{% load compress %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{% block appName %}{% endblock appName %}{% block pageName %}{% endblock pageName %}</title>

        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

        <link href="{% static 'lib/font-awesome-4.2.0/css/font-awesome.min.css' %}" rel="stylesheet">
            <link href="{% static 'lib/bootstrap3/css/bootstrap.min.css' %}" rel="stylesheet">
            <script src="{% static 'lib/jquery-1.11.1.min.js' %}"></script>
        {% compress css %}
            <link href="{% static 'css/offcanvas.css' %}" rel="stylesheet">
        {% endcompress %}
        {% compress js %}
            <script src="{% static 'lib/ie-emulation-modes-warning.js' %}"></script>
            
        {% endcompress %}
        {% block extraCss %}
        {% endblock extraCss %}

        {% block extraJsLib %}
        {% endblock extraJsLib %}


    </head>
    <body>
        <div id="wrap">
            <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
                <div class="container">
                    {% include "nav.html" %}
                </div><!-- /.container -->
            </nav><!-- /.navbar -->
            <div class="container">
                <div class="row row-offcanvas row-offcanvas-right">
                    {% block content %}
                    {% endblock content %}
                </div><!--/row-->
            </div>
        </div>
        <footer class="center broke-endless-pages">
                Since 2014
        </footer>
        <script src="{% static 'lib/bootstrap3/js/bootstrap.min.js' %}"></script>
        {% compress js %}
        
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        
        <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
        <script src="{% static 'js/offcanvas.js' %}"></script>
        {% endcompress %}
        {% block extraJs %}
        {% endblock extraJs %}
    </body>
</html>

wsgi/source/templates/base.jinja
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{% block appName %}{% endblock appName %}-{% block pageName %}{% endblock pageName %}</title>
        <!-- Bootstrap core CSS -->
        <link href="{{ static('lib/bootstrap3/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{{ static('css/offcanvas.css') }}" rel="stylesheet">
        
        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="{{ static('lib/ie-emulation-modes-warning.js') }}"></script>
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        {% block extraJsLib %}
        {% endblock extraJsLib %}
        
        {% block extraCss %}
        {% endblock extraCss %}
    </head>
    <body>
        <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
            <div class="container">
                {% include "nav.jinja" %}
            </div><!-- /.container -->
        </nav><!-- /.navbar -->
        <div class="container">
            <div class="row row-offcanvas row-offcanvas-right">
                {% block content %}
                {% endblock content %}
            </div><!--/row-->
            <hr>
            <footer class="center">
                <p>&copy; Company 2014</p>
            </footer>
        </div><!--/.container-->
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{{ static('lib/jquery-1.11.1.min.js') }}"></script>
        <script src="{{ static('lib/bootstrap3/js/bootstrap.min.js') }}"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="{{ static('js/ie10-viewport-bug-workaround.js') }}"></script>
        <script src="{{ static('js/offcanvas.js') }}"></script>
        {% block extraJs %}
        {% endblock extraJs %}
    </body>
</html>

wsgi/source/templates/digg_paginator.html
{% spaceless %}
  {% if has_previous %}
    <li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}page={{ previous }}">&laquo; Prev</a></li>
  {% endif %}
  {% if not in_leading_range %}
    {% for p in pages_outside_trailing_range %}
      <li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}page={{ p }}">{{ p }}</a></li>
    {% endfor %}
    <li><span class="ellipsis">...</span></li>
  {% endif %}
  {% for p in page_range %}
    {% if p == page %}
      <li><span class="active">{{ p }}</span></li>
    {% else %}
      <li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}page={{ p }}">{{ p }}</a></li>
    {% endif %}
  {% endfor %}
  {% if not in_trailing_range %}
    <li><span class="ellipsis">...</span></li>
    {% for p in pages_outside_leading_range reversed %}
      <li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}page={{ p }}">{{ p }}</a></li>
    {% endfor %}
  {% endif %}
  {% if has_next %}
    <li><a href="{% if get_params %}?{{ get_params }}&{% else %}?{% endif %}page={{ next }}">Next &raquo;</a></li>
  {% endif %}
{% endspaceless %}

wsgi/source/templates/form.html
<form method="POST" action="{{action|default:''}}"class="well" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send">
    <input type="button" value="Back" onClick="history.go(-1);return true;">
</form>

wsgi/source/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="app-list row">
   <div class="col-sm-3 item"><a href="{% url 'blog:entry:list' %}">Blog</a></div>
   <div class="col-sm-3 item"><a href="{% url 'account:index' %}">Account</a></div>
</div>
{% endblock content %}

{% block extraJs %}
<script>
    var colors = ['#663399', '#674172', '#446CB3', '#22313F', '#3A539B', '#26A65B', '#1BBC9B', '#1E824C', '#EB9532'];
    $(".app-list > .item").each(function( index ) {
        $(this).css("background-color",colors[Math.floor(Math.random() * colors.length)]);
    });
</script>
{% endblock extraJs %}

wsgi/source/templates/nav.html
<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'index' %}"><i class="fa fa-home fa-2x"></i>
</a>
</div>
<div id="navbar" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">

        <!--
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul role="menu" class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
        </ul>
        </li>
        -->

    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'blog:entry:list' %}">Blog</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'todo:list:list' %}">Todo</a></li>
        {% endif %}
        <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="false">ACCOUNT <span class="caret"></span></a>
        {% if user.is_authenticated %}
        
            <ul role="menu" class="dropdown-menu">
                <li><a href="{% url 'account:logout' %}">Logout</a></li>
                <li><a href="{% url 'account:changepassword' %}">Change Password</a></li>
            </ul>
        {% else %}
            <ul role="menu"  class="dropdown-menu">
            <li><a href="{% url 'account:login' %}">Login</a></li>
            {% if OPEN_REGISTER %}
                <li><a href="{% url 'account:register' %}">Register</a></li>
            {% endif %}
            </ul>
        {% endif %}
        </li>
        
        <!--
        <li><a href="#">Settings</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Help</a></li>
        -->
    </ul>
    <!--
    <form class="navbar-form navbar-right">
        <input type="text" placeholder="Search..." class="form-control">
    </form>
    -->
</div><!-- /.nav-collapse -->

wsgi/source/templates/nav.jinja
<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{url('index')}}">Lee's APP</a>
</div>
<div id="navbar" class="collapse navbar-collapse">
    <ul class="nav navbar-nav">

        <!--
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul role="menu" class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
        </ul>
        </li>
        -->

    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ url('blog:entry:list')}}">Blog</a></li>
        <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#" aria-expanded="false">ACCOUNT <span class="caret"></span></a>
        {% if user.is_authenticated %}
            <ul role="menu" class="dropdown-menu">
                <li><a href="{{ url('account:logout')}}">Logout</a></li>
                <li><a href="{{ url('account:changepassword')}}">Change Password</a></li>
            </ul>
        {% else %}
            <ul role="menu"  class="dropdown-menu">
            <li><a href="{{ url('account:login')}}">Login</a></li>
            {% if OPEN_REGISTER %}
                <li><a href="{{ url('account:register')}}">Register</a></li>
            {% endif %}
            </ul>
        {% endif %}
        </li>
        <!--
        <li><a href="#">Settings</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Help</a></li>
        -->
    </ul>
    <!--
    <form class="navbar-form navbar-right">
        <input type="text" placeholder="Search..." class="form-control">
    </form>
    -->
</div><!-- /.nav-collapse -->

wsgi/source/templates/pagination.html
{% load getpages_tags %}
{% if is_paginated %}
    <div class="pagination" algin="center">
        <ul class="pagination pagination-sm">
            {% if page_obj.has_previous %}
                <li><a href="{% url_add_query page=page_obj.previous_page_number %}">&larr;</a>
            {% else %}
                <li class="disabled"><a>&larr;</a>
            {% endif %}
            {% for num in page_obj.page_range %}
               {% if not num %}
                    <li class="disabled"><a>...</a></li>
               {% else %}
                   <li {% if num == page_obj.number %}class="active"{% endif %}>
                        <a href="{% url_add_query page=num %}">{{ num }}</a>
                    </li>
               {% endif %}

            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="{% url_add_query page=page_obj.next_page_number %}">&rarr;</a>
            {% else %}
                <li class="disabled"><a>&rarr;</a>
            {% endif %}
        </ul>
    </div>
{% endif %}

wsgi/source/templates/pagination_backup.html
{% if is_paginated %}
    <div class="pagination" algin="center">
        <ul class="pagination pagination-sm">
            {% if page_obj.has_previous %}
                <li><a href="./?page={{ page_obj.previous_page_number }}">&larr;</a>
            {% else %}
                <li class="disabled"><a>&larr;</a>
            {% endif %}
            {% for num in page_obj.page_range %}
               {% if not num %}
                    <li class="disabled"><a>...</a></li>
               {% else %}
                   <li {% if num = page_obj.number %}class="active"{% endif %}>
                        <a href="./?page={{ num }}">{{ num }}</a>
                    </li>
               {% endif %}

            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="./?page={{ page_obj.next_page_number }}">&rarr;</a>
            {% else %}
                <li class="disabled"><a>&rarr;</a>
            {% endif %}
        </ul>
    </div>
{% endif %}