wsgi/source/apps/account/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from .views import IndexView, LoginView, LogoutView, CreateUser, ChangePassWordView, PasswordResetConfirmView, ResetPasswordRequestView
from django.conf import settings


urlpatterns = patterns(
    '',
    url(r'^index/$', IndexView.as_view(), name='index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^changepassword/$', ChangePassWordView.as_view(),
        name='changepassword'),
)
if settings.OPEN_REGISTER:
    urlpatterns += patterns(
        '',
        url(r'^register/$', CreateUser.as_view(), name='register'),
    )
if settings.OPEN_FORGET_PASSWORD:
    urlpatterns += patterns(
        '',
        url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            PasswordResetConfirmView.as_view(), name='reset_password_confirm'),
        url(r'^reset_password/$', ResetPasswordRequestView.as_view(),
            name="reset_password"),
    )

wsgi/source/apps/blog/urls.py
from __future__ import absolute_import
from django.conf.urls import patterns, url, include
from . import views
from django.conf import settings

entry_patterns = patterns(
    '',
    url(r'^$', views.EntryListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.EntryDetailView.as_view(), name='detail'),
    url(r'^create/$', views.EntryCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$',
        views.EntryUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$',
        views.EntryDeleteView.as_view(), name='delete'),
)
tag_patterns = patterns(
    '',
    url(r'^$', views.TagListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.TagEntryListView.as_view(),
        name='tagToEntry'),
    url(r'^create/$', views.TagCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$',
        views.TagUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$',
        views.TagDeleteView.as_view(), name='delete'),
    url(r'^notag/$', views.NoTagEntryListView.as_view(), name='noTagList'),
)
comment_patterns = patterns(
    '',
    url(r'^(?P<pk>\d+)/$', views.CommentDetailView.as_view(),
        name='detail'),
    url(r'^update/(?P<pk>\d+)/$', views.CommentUpdateView.as_view(),
        name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.CommentDeleteView.as_view(),
        name='delete'),
)


urlpatterns = patterns(
    '',
    url(r'^entry/', include(entry_patterns, namespace='entry')),
    url(r'^tag/', include(tag_patterns, namespace='tag')),
    url(r'^comment/', include(comment_patterns, namespace='comment')),

    #url(r'^search/$', views.MySearch, name='search')
)
if settings.SEARCH_ENGINE == 'HAYSTACK':
    urlpatterns += patterns(
        '',
        url(r'^search/$', views.search, name='search'),
    )
else:
    urlpatterns += patterns(
        '',
        url(r'^search/$', views.WatsonSearchListView.as_view(), name='search'),
    )

wsgi/source/etc/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView
from apps.blog.sitemaps import EntrySiteMap

urlpatterns = patterns(
    '',
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^account/', include('apps.account.urls', namespace='account')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', RedirectView.as_view(pattern_name = 'blog:entry:list'), name="index"),
    url(r'^todo/', include('apps.todo.urls', namespace='todo')),
)

if settings.SEARCH_ENGINE == 'HAYSTACK':
    urlpatterns += patterns(
        '',
        url(r'^search/', include('haystack.urls')),
    )

# debug toolbar
# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += patterns(
#         '',
#         url(r'^__debug__/', include(debug_toolbar.urls)),
#     )

sitemaps = {
    'blog': EntrySiteMap,
}
urlpatterns += (
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

wsgi/source/apps/blog/forms.py
from __future__ import absolute_import
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit, Fieldset, Field, Button, Div
from .models import Entry, Tag, Comment
from pagedown.widgets import AdminPagedownWidget
from crispy_forms.bootstrap import FormActions


class EntryForm(forms.ModelForm):
    description = forms.CharField(widget=AdminPagedownWidget())

    class Meta:
        fields = ('title', 'description', 'tag')
        model = Entry

    def __init__(self, action='', *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'EntryForm'
        self.helper.form_method = 'POST'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-2'
        self.helper.field_class = 'col-sm-8'
        self.helper.form_action = action
        self.helper.layout = Layout(
            Fieldset(
                'Entry',
                'title',
                'description',
                'tag',
            ),
            FormActions(
                Submit('submit', 'Submit', css_class="btn-primary"),
                Button('cancel', 'Cancel', onclick='history.go(-1);')
            )
        )

    def save(self, submitter=None, *args, **kwargs):
        if not self.instance.pk:
            self.instance.submitter = submitter
        return super().save()


class CommentForm(forms.ModelForm):
    description = forms.CharField(widget=AdminPagedownWidget())

    class Meta:
        model = Comment
        fields = ('title', 'description')

    def __init__(self, title=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'CommentForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-2'
        self.helper.field_class = 'col-sm-8'
        self.helper.form_method = 'POST'
        self.fields['title'].initial = title
        self.helper.layout = Layout(
            Fieldset(
                'Comment',
                'title',
                'description',
            ),
            FormActions(
                Submit('submit', 'Submit', css_class="btn-primary"),
                Button('cancel', 'Cancel', onclick='history.go(-1);')
            )
        )

    def save(self, entry=None, submitter=None, *args, **kwargs):
        if not self.instance.pk:
            self.instance.entry = entry
            self.instance.submitter = submitter
        return super().save(*args, **kwargs)


class TagForm(forms.ModelForm):

    class Meta:
        fields = ('title',)
        model = Tag

    def __init__(self, action='', *args, **kwargs):
        super(TagForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'TagForm'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-sm-2'
        self.helper.field_class = 'col-sm-8'
        self.helper.form_method = 'POST'
        self.helper.form_action = action
        self.helper.layout = Layout(
            Fieldset(
                'Tag',
                'title',
            ),
            FormActions(
                Submit('submit', 'Submit', css_class="btn-primary"),
                Button('cancel', 'Cancel', onclick='history.go(-1);')
            )
        )


class SearchForm(forms.Form):
    q = forms.CharField(label='Search', max_length=50)

    def __init__(self, q=None, action=None, *args, **kwargs):
        super(SearchForm, self).__init__(*args, **kwargs)
        self.fields['q'].initial = q
        self.helper = FormHelper(self)
        self.helper.form_id = 'SearchForm'
        self.helper.form_class = 'searchform form-inline'
        self.helper.label_class = 'col-sm-3'
        self.helper.field_class = 'col-sm-8'
        self.helper.form_method = 'GET'
        self.helper.form_action = action
        #self.helper.template = 'bootstrap/table_inline_formset.html'

        #self.helper.add_input(Submit('submit', 'Submit'))
        # self.helper.layout = Layout(
        #    Field('q',),
        #)

wsgi/source/apps/blog/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.http import Http404
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView)
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from . import forms
from . import models
from django.core.urlresolvers import reverse_lazy
import json
from django.db.models import Count
from django.contrib import messages
from django.views.generic.detail import SingleObjectMixin
from utils.decorators import my_login_required
from utils import mixins
import watson
from django.conf import settings
"""
class LoggedInMixin(object):

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            raise Http404
        return super(LoggedInMixin, self).dispatch(request, *args, **kwargs)
"""


class CommonMixin(object):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagside'] = models.Tag.objects.by_entrys()[:5]
        # context['tagform'] = forms.TagForm(
        #    action=reverse_lazy('blog:tag:ajaxUpdate'))
        return context

"""
def user_permitted(function):
    def decorator(function):
        def _wrapped_view(request, *args, **kwargs):
            # get obj from request
            if obj.user != request.user or (not request.user.is_superuser):
                return HttpResponseRedirect(reverse('forbidden'))
            return function(request, *args, **kwargs)
        return _wrapped_view
    return decorator(function)
"""


class EntryMixin(CommonMixin):

    """
    Entry Mixin
    model : Entry
    queryset: add annotate, count relate comment ammounts
    """
    queryset = models.Entry.objects.all()


class EntryListView(EntryMixin, mixins.PaginatorMixin, ListView):

    """
    List all Entry
    """
    #model = models.Entry
    queryset = models.Entry.getAnnotate()
    template_name = "blog/index.html"
    context_object_name = "entrys"


class EntryDetailView(EntryMixin, SingleObjectMixin, ListView):

    """
    Entry Detail
    accept comment post
    comment Form init the title to relate Entry title

    if comment post is ok, redirect to relate Entry
    """
    form_class = forms.CommentForm
    template_name = "blog/entryDetail.html"
    paginate_by = 5
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        # here set we want to query(Tag model), overridden get_object's
        # queryset
        self.object = self.get_object(queryset=models.Entry.getAnnotate())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entry'] = self.object
        context['form'] = self.form_class(
            title=('RE:' + self.object.getTitle()))
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            messages.add_message(
                self.request, messages.SUCCESS, 'comment create success')
            #obj = self.get_object()
            obj = self.get_object(queryset=models.Entry.objects.all())
            form.save(submitter=request.user, entry=obj)
            return redirect(obj)
        else:
            return self.get(request, *args, **kwargs)

    def get_queryset(self):
        # get the entry relate comments
        # print('call')
        return self.object.comment_set.all()


class EntryCreateView(mixins.LoginRequiredMixin, EntryMixin, CreateView):

    """
    Entry Create
    """
    model = models.Entry
    form_class = forms.EntryForm
    template_name = "blog/form.html"

    def form_valid(self, form):
        self.object = form.save(submitter=self.request.user)
        return redirect(self.object)


class EntryUpdateView(mixins.OwnerOrSuperuserMixin, EntryMixin, UpdateView):

    """
    Entry Create
    """
    form_class = forms.EntryForm
    model = models.Entry
    template_name = "blog/form.html"


class EntryDeleteView(mixins.OwnerOrSuperuserMixin, EntryMixin, DeleteView):
    model = models.Entry
    success_url = reverse_lazy('blog:entry:list')
    form_class = forms.EntryForm
    template_name = "blog/comfirm_delete.html"


class TagMixin(CommonMixin):
    form_class = forms.TagForm
    queryset = models.Tag.objects.all()


class TagListView(TagMixin, ListView):
    template_name = "blog/tagList.html"
    context_object_name = "tags"
    queryset = models.Tag.getAnnotate()


class TagEntryListView(TagMixin, SingleObjectMixin, mixins.PaginatorMixin, ListView):

    """
    Entry queryset for use by ListView
    Tag queryset for use in get_object() will call get
    get_object() default will call get_queryset(), but it is not I want
    overridden return Entry instead of Tag
    """
    paginate_by = 10
    template_name = "blog/tagEntryList.html"

    def get(self, request, *args, **kwargs):
        # here set we want to query(Tag model)
        self.object = self.get_object(queryset=models.Tag.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.object
        return context

    def get_queryset(self):
        # get the tag relate entrys
        return self.object.entry_set.all().annotate(comment_count=Count('comment'))


class TagCreateView(mixins.SuperUserCheckMixin, TagMixin, CreateView):

    template_name = "blog/form.html"


class TagUpdateView(mixins.SuperUserCheckMixin, TagMixin, UpdateView):
    # success_url = reverse_lazy('blog:entry:list')
    template_name = "blog/form.html"


class TagDeleteView(mixins.SuperUserCheckMixin, TagMixin, DeleteView):
    success_url = reverse_lazy('blog:tag:list')
    template_name = "blog/comfirm_delete.html"


class NoTagEntryListView(EntryMixin, mixins.PaginatorMixin, ListView):
    template_name = "blog/tagEntryList.html"
    context_object_name = "entrys"
    queryset = models.Entry.objects.filter(tag=None).annotate(
        comment_count=Count('comment'))
    paginate_by = '10'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = 'NO SELECT TAG'
        return context
"""
@login_required
def ajaxUpdateTag(request):
    if request.method == 'POST' and request.is_ajax():
        tagname = request.POST['title']
        tag, status = models.Tag.objects.get(title=tagname)
        if status:
            tag.title = tagname
            tag.save()
            return HttpResponse(json.dumps({'error': 'false', 'message': 'update success', 'tagname': tag.title}))
        else:
            return HttpResponse(json.dumps({'error': 'true', 'message': 'tag exist, try another.'}))
    else:
        raise Http404
"""


class CommentMixin(CommonMixin):
    model = models.Comment
    form_class = forms.CommentForm


class CommentDetailView(CommentMixin, DeleteView):
    template_name = "blog/commentDetail.html"
    context_object_name = "comment"


class CommentUpdateView(mixins.OwnerOrSuperuserMixin, CommentMixin, UpdateView):
    template_name = "blog/form.html"

    def get_success_url(self):
        return self.object.get_relate_entry_url()


class CommentDeleteView(mixins.OwnerOrSuperuserMixin, CommentMixin, DeleteView):
    template_name = 'blog/comfirm_delete.html'

    def get_success_url(self):
        return self.object.get_relate_entry_url()


if settings.SEARCH_ENGINE == 'HAYSTACK':
    #from haystack.forms import HighlightedSearchForm, ModelSearchForm
    from haystack.views import SearchView, search_view_factory
    from haystack.query import SearchQuerySet

    sqs = SearchQuerySet().models(models.Entry)

    class MySearch(CommonMixin, SearchView):

        def extra_context(self):
            context = {}
            context['tagside'] = models.Tag.objects.by_entrys()[:5]
            return context

    def search(request):
        sqs = SearchQuerySet().models(models.Entry, models.Comment)
        view = search_view_factory(
            view_class=MySearch,
            template='blog/search.html',
            searchqueryset=sqs,
            form_class=HighlightedSearchForm
        )
        return view(request)
else:
    class WatsonSearchListView(CommonMixin, mixins.PaginatorMixin, ListView):

        """
        search comment and entry
        """
        template_name = "blog/watson_search.html"
        #context_object_name = "entrys"
        models = (models.Entry, models.Comment)

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            print(self.request.GET.get('q', None))
            context['form'] = forms.SearchForm(q=self.request.GET.get('q'))
            return context

        def get_models(self):
            return self.models

        def get_queryset(self):
            """
            Return the list of items for this view.
            The return value must be an iterable and may be an instance of
            `QuerySet` in which case `QuerySet` specific behavior will be enabled.
            """
            query_string = self.request.GET.get('q')
            if query_string:
                result = watson.search(query_string, models=self.get_models())
                return result
            # return empty query set
            return models.Entry.objects.none()

wsgi/source/apps/blog/templates/blog/base.html
{% extends "base.html" %}
{% load static %}
{% load compress %}
{% block appName %}Blog{% endblock appName %}

{% block extraCss %}
    {{ form.media }}
    {% compress css %}
        <link href="{% static 'blog/blog.css' %}" rel="stylesheet" />
        <link rel="stylesheet" type="text/css" href="{% static 'lib/highlight/styles/monokai_sublime.css' %}">
    {% endcompress %}
{% endblock extraCss %}


{% block content %}
<nav id="sidebar" class="col-sm-3"><!--nav-->
    {% include "blog/slidebar.html" %}
</nav>
<div id="content" class="col-sm-9">
    <div id="messages">
        {% for message in messages %}
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
                <i class="fa fa-info"></i>
                {{ message }}
            </div>
        {% endfor %}
    </div>
    {% block body %}
        this is body
    {% endblock body %}
</div>
{% endblock content %}


{% block extraJs %}
    {% compress js %}
        <script src="{% static 'lib/highlight/highlight.pack.js' %}"></script>
        <script type="text/javascript">
            hljs.initHighlightingOnLoad();
        </script>
    {% endcompress %}
{% endblock extraJs %}

wsgi/source/apps/blog/templates/blog/comfirm_delete.html
{% extends "blog/base.html" %}
{% load static %}
{% block pageName %}Delete-{{object.title}}{% endblock pageName %}
{% block body %}
    <h3>do you really want to delete this {{object.getModelName}} - {{object.getTitle}}</h3>
    {% include "form.html" %}
{% endblock body %}

wsgi/source/apps/blog/templates/blog/commentBlock.html
{% load blog_permission %}
{% load description_markdown %}
<div class="comment row">
    <div class="headline col-sm-12">
        <a href="{{comment.get_absolute_url}}">{{comment.getTitle}}</a>
    </div>
    <div class="col-sm-12">
        <ul class="meta">
            <li class="written">{{comment.getSubmitter}}</li>
            <li class="time">{{comment.getSubmittedOn|date:"d M Y"}}</a></li>
            {% if comment|has_perm:user %}
                <li><a class="edit" href="{{comment.get_update_url}}">Edit</a></li>
                <li><a class="delete" href="{{comment.get_delete_url}}">Delete</a></li>
            {% endif %}
            <li class="up"><a href="{{comment.get_relate_entry_url}}">Up</a></li>
        </ul>
    </div>
    <div class="description col-sm-12">
      {{comment.getDescription|md|safe}}
    </div>
</div>

wsgi/source/apps/blog/templates/blog/commentDetail.html
{% extends "blog/base.html" %}
{% load static %}
{% block pageName %}comment-{{object.title}}{% endblock pageName %}
{% block body %}
<div class="comment-detail">
    {% include "blog/commentBlock.html" %}
</div>
{% endblock body %}

wsgi/source/apps/blog/templates/blog/entryBlock.html
{% load blog_permission %}
<div class="row">
    <div class="headline col-sm-12">
        <a href="{{entry.get_absolute_url}}">{{entry.getTitle}}</a>
    </div>
    <div class="col-sm-12">
        <ul class="meta">
            <li class="written">{{entry.getSubmitter}}</li>
            <li class="time">{{entry.getSubmittedOn|date:"d M Y"}}</a></li>
            {% for tag in entry.getRelateTags %}
                <li><a class="relate-tag" href="{{tag.get_absolute_url}}">{{tag}}</a></li>
            {% endfor %}
            <li class="count_comment">comments({{entry.comment_count}})</li>
            {% if entry|has_perm:user %}
                <li><a class="edit" href="{{entry.get_update_url}}">Edit</a></li>
                <li><a class="delete" href="{{entry.get_delete_url}}">Delete</a></li>
            {% endif %}
        </ul>
    </div>
</div>

wsgi/source/apps/blog/templates/blog/entryDetail.html
{% extends "blog/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load description_markdown %}
{% block pageName %}Entry-{{object.title}}{% endblock pageName %}
{% block body %}
    <div class="entry">
        {% include "blog/entryBlock.html" %}
        <div class="description">
           {{entry.getDescription|md|safe}}
        </div>
    </div>




    <div class="row">
        {% if page_obj %}
        <div class="comments col-sm-10 col-sm-offset-2">
            {% for comment in page_obj %}
                {% include "blog/commentBlock.html" %}
            {% endfor %}
        </div>
        <div class="text-center row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                {% include "pagination.html" %}
            </div>
        </div>
        {% endif %}
        <div class="col-sm-10 col-sm-offset-2">
        {% if user.is_authenticated %}

            {% crispy form %}

        {% else %}



            <p class="info">Want to comment this entry?<a href="{% url 'account:login' %}">Login</a>{% if OPEN_REGISTER %} or <a href="{% url 'account:register' %}">Register</a>{% endif %}</p>
        {% endif %}
        </div>
    </div>
{% endblock body %}

wsgi/source/apps/blog/templates/blog/entrysajax.html
{% load endless %}
    {% if entrys %}
        {% paginate entrys %}
        <ul class="entrys">
            {% for entry in entrys %}
            <li class="entry">
                {#{{forloop.counter0|add:page_obj.start_index }}#}
                {% include "blog/entryBlock.html" %}
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Sorry, no entry at this moment</p>
    {% endif %}



    <div class="text-center row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

{% get_pages %}
{% if pages.paginated %}
    Some info/layout to display only if the available
    objects span multiple pages...
    {{ pages }}
{% endif %}

        </div>
    </div>

wsgi/source/apps/blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load static %}

{% block pageName %}List{% endblock pageName %}

{% block body %}
    
    {% if entrys %}
        <ul class="entrys">
            {% for entry in entrys %}
            <li class="entry">
                {#{{forloop.counter0|add:page_obj.start_index }}#}
                {% include "blog/entryBlock.html" %}
            </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Sorry, no entry at this moment</p>
    {% endif %}



    <div class="text-center row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% include "pagination.html" %}
        </div>
    </div>
{% endblock body %}

wsgi/source/apps/blog/templates/blog/search.html
{% extends "blog/base.html" %}
{% load static %}
{% block pageName %}Search{% endblock pageName %}
{% block body %}
    {#<p>search:{{query}}</p>#}
    <form class="searchform" method="get">
        {{form.as_p}}
    </form>
    {% comment %}


    {{page}}
    {{suggestion}}
    {{searchqueryset}}
    {% for result in page.object_list %}
    <div class="search_result">
        <h3><a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a></h3>

        <p>{{ result.object.body|truncatewords:80 }}</p>
    </div>
    {% empty %}
        <p>Sorry, no results found.</p>
    {% endfor %}
    {% endcomment %}
    {% if page.object_list %}
    <div>
        <ul class="searchlist">
            {% for result in page.object_list %}
            <li class="item">
                <div>
                    <div class="headline"><a href="{{ result.object.get_absolute_url }}">{{result.title}}</a></div>
                    <div class="meta">
                        <ul>
                            <li class="written">{{result.object.getSubmitter}}</li>
                            <li class="time">{{result.object.getSubmittedOn|date:"d M Y"}}</li>
                        </ul>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    {% else %}
        <p class="info">Sorry, result is empty</p>
    {% endif %}

    <div class="text-center row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% include "pagination.html" %}
        </div>
    </div>
    {% comment %}
    {% for result in page.object_list %}
    <div class="search_result">
        <h3><a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a></h3>

        <p>{{ result.object.body|truncatewords:80 }}</p>
    </div>
    {% empty %}
        <p>Sorry, no results found.</p>
    {% endfor %}
    {% endcomment %}
{% endblock body %}

wsgi/source/apps/blog/templates/blog/slidebar.html
{% load crispy_forms_tags %}
{% load static %}
<div class="row">
    {% comment %}
    <div class="col-sm-12">
        <img src="{% static "img/camel.png" %}" alt="test" class="img-thumbnail img-responsive center" />
    </div>
    {% endcomment %}
    <div class="col-sm-12">
        <ul>
            <li class="item"><a class="home" href="{% url 'blog:entry:list' %}">Home</a></li>
            <li class="item"><a class="add" href="{% url 'blog:entry:create' %}">Entry</a></li>
            <li class="item"><a class="add" href="{% url 'blog:tag:create' %}">Tag</a></li>
            <li class="item"><a class="relate-tag" href="{% url 'blog:tag:list' %}">Relate Tag</a></li>
        </ul>
    </div>
    <div class="col-sm-12">
        <form id="searchform" role="form" class="form-inline" action="{% url 'blog:search' %}" method="get">
            <input type="text" name="q" placeholder="search it">
        </form>
    </div>
    {% include "blog/tagscroll.html" %}
</div>

wsgi/source/apps/blog/templates/blog/tagBlock.html
<div class="row">
    {% if user.is_superuser %}
        <div class="col-sm-6">
            <a class="relate-tag" href="{{tag.get_absolute_url}}">{{tag}}({{tag.entry_count}})</a>
        </div>
        <div class="col-sm-1">
            <a class="edit" href="{{tag.get_update_url}}"></a>
        </div>
        <div class="col-sm-1">
            <a class="delete" href="{{tag.get_delete_url}}"></a>
        </div>
    {% else %}
        <div class="col-sm-12">
            <a class="relate-tag" href="{{tag.get_absolute_url}}">{{tag}}({{tag.entry_count}})</a>
        </div>
    {% endif %}

</div>

wsgi/source/apps/blog/templates/blog/tagEntryList.html
{% extends "blog/base.html" %}
{% load static %}
{% block pageName %}Tag-{{tagname}}{% endblock pageName %}
{% block body %}
    <div class="headline text-center">
        Tag : {{tagname}}
    </div>
    <div>
        <ul class="entrys">
            {% for entry in page_obj %}
                <li class="entry">
                {% include "blog/entryBlock.html" %}
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="text-center row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            {% include "pagination.html" %}
        </div>
    </div>
{% endblock body %}